### ISSUE TITLE
Can't get Vehicle Camera Movement to work

### ISSUE THREAD

**Issue by SodaMazing** [ThirteenAG/III.VC.SA.CLEOScripts#1]
I'm able to run the other scripts just fine, but Vehicle Camera Movement doesn't work for me.  

I'm running GTA 3 version 1.1 on Steam, CLEO version 2.0.0.5 and GInput version 1.11

**Comment by ThirteenAG** [comment]
Version 1.1 is not compatible in most cases. Get version 1.0 and you might wanna use this instead: https://gtaforums.com/topic/896122-classic-axis-visual-camera-improvements/

These scripts are currently not maintained.
